### ISSUE TITLE
Need illustrator open .ait script

### ISSUE THREAD

**Issue by sgops27** [LukaszGrela/IllustratorScripts-mobile-dev#1]
I have created some illustrator template files (.ait) placed in my local D drive (path),
Ex: 00_Helvetica_27 x 40, 00_Helvetica_28 x 47 (and Many)

once I run the script open that popup template file (attached i create the screenshot) window and select what file i need then hit OK open that file.

it's passable in javascript
![WhatsApp Image 2019-02-28 at 9 57 11 AM](https://user-images.githubusercontent.com/47688301/54736919-72ef9f80-4bd3-11e9-8e97-239390ff0dd5.jpeg)

**Comment by LukaszGrela** [comment]
Look [here (adobe.com)](https://www.adobe.com/devnet/illustrator/scripting.html) to select appropriate scripting guide and search for a file system access, if there is none available than you can't load a content of a file into your script.

**Comment by sgops27** [comment]
Actually, my team is more than 15 peoples, so we need quality and consistency fonts and font size, many things, i have fixed all in our template files (.ait). that files placed in server path Ex:\\172.24.161.52\books\Template (already we have used the 
script attached here but that script decoded) my old server some space problem, (we need more sapce) so they are allocated the new server in my team, now that script is not working we unable to change server path that script it's decoded so pls help me.
[Template.zip](https://github.com/LukaszGrela/IllustratorScripts-mobile-dev/files/2994844/Template.zip)
